contact_links:
  - name: Discord
    url: https://discord.gg/mYKK4BwGxe
    about: The JDA-C Discord is the best place to receive fast support for your questions.
  - name: Releases
    url: https://github.com/BlockyDotJar/JDA-Commons/releases
    about: You can find the latest releases here on GitHub.
  - name: Questions
    url: https://github.com/BlockyDotJar/JDA-Commons/discussions
    about: You can ask questions about JDA/JDA-C and find useful information in our discussions.